print("a. Các kiểu dữ liệu trong Python:")
print("- Kiểu dữ liệu Số: ")
print("+ int: Kiểu số nguyên (VD: 5, 10).")
print("+ float: Kiểu số thực (VD: 3.14, -0.25).")
print("+ complex: Kiểu số phức (VD: 1+2j).")
print("- Kiểu dữ liệu Chuỗi: ")
print("+ str: Kiểu chuỗi kí tự (VD: Chào bạn).")
print("- Kiểu dữ liệu Seuquence: ")
print("+ list: Kiểu danh sách các phần tử, có thể thay đổi (VD: 1, 2, Python).")
print("+ tuple: Kiểu bộ danh sách các phần tử cố định, không thể thay đổi sau khi tạo (Ví dụ: 1, 2, 3).")
print("+ range: Kiểu phạm vi.")
print("- Kiểu dữ liệu Nhị phân: ")
print("+ bytes: Chuỗi byte không thể thay đổi (immutable). Dùng để lưu trữ dữ liệu cố định như hình ảnh hoặc file.")
print("+ bytearray: Mảng byte có thể thay đổi (mutable). Cho phép bạn sửa đổi, thêm hoặc xóa các byte trực tiếp.")
print("+ memoryview: : Cung cấp giao diện xem bộ nhớ đệm (buffer protocol), cho phép thao tác trên dữ liệu nhị phân (như của bytes hoặc bytearray) mà không cần tốn bộ nhớ sao chép dữ liệu.")
print("- Kiểu dữ liệu Dictionary:")
print("+ dict: Kiểu từ điển, lưu trữ dữ liệu dưới dạng cặp key: value (Ví dụ: {age: 20}).")
print("- Kiểu dữ liệu Boolen:")
print("+ bool: Chỉ nhận một trong hai giá trị True hoặc False.")
print("- Kiểu dữ liệu Set:")
print("+ set: Tập hợp các phần tử không trùng lặp và không có thứ tự (Ví dụ: {1, 2, 3}).")
print("- Kiểu dữ liệu None: Nonetype.")
print("b. Các toán tử trong Python:")
print("- Toán tử số học: + (cộng), - (trừ), * (nhân), / (chia lấy số thực), // (chia lấy nguyên), % (chia lấy dư), ** (mũ/lũy thừa).")
print("- Toán tử quan hệ: == (bằng), != (khác), > (lớn hơn), < (nhỏ hơn), >= (lớn hơn hoặc bằng), <= (nhỏ hơn hoặc bằng).")
print("- Toán tử gán: =, +=, -=, *=, /=, //=, %=, **=.")
print("- Toán tử logic: and (và), or (hoặc), not (phủ định).")
print("- Toán tử thao tác bit: so sánh các bit ở cùng vị trí của hai số với nhau, nếu giống nhau thì trả về giá trị 1 và khác nhau thì trả về giá trị 0.")
print("- Toán tử membership: in (thuộc), not in (không thuộc) — dùng để kiểm tra một phần tử có nằm trong tập hợp/chuỗi/list hay không.")
print("- Toán tử identify: is (là), is not (không phải là) — dùng để kiểm tra xem hai biến có cùng trỏ vào một đối tượng hay không.")
print("c. Mệnh đề điều kiện và vòng lặp")
print("- Mệnh đề điều kiện: Cho phép chúng ta thực hiện các đoạn code khác nhau dựa trên một điều kiện nào đó. Trong Python, chúng ta sử dụng các từ khóa if, elif (else if), và else để tạo câu điều kiện.")
print("+ if: Kiểm tra điều kiện đầu tiên. Nếu điều kiện này đúng, đoạn code bên trong khối if sẽ được thực thi.")
print("+ elif (viết tắt của else if): Kiểm tra điều kiện tiếp theo chỉ khi các điều kiện if và elif ở phía trên đều sai.")
print("+ else: Đóng vai trò là phương án cuối cùng, khối lệnh này sẽ chạy khi tất cả các điều kiện if và elif phía trên đều không thỏa mãn")
print("- Vòng lặp: Vòng lặp cho phép chúng ta thực hiện một đoạn code nhiều lần. Trong Python, chúng ta sử dụng hai loại vòng lặp chính: for và while.")
print("+ Vòng lặp for (số lần xác định) được sử dụng để lặp qua một chuỗi (string), list, tuple, set, dictionary, hoặc bất kỳ đối tượng iterable nào khác.")
print("+ Vòng lặp while (số lần không xác định) được sử dụng để thực hiện một đoạn code cho đến khi một điều kiện nào đó không còn đúng nữa.")
print("d. Kiểu dữ liệu True/ Flase:")
print("+ True và False là hai giá trị duy nhất thuộc kiểu dữ liệu Boolean(bool).")
print("+ Lưu ý cú pháp: Trong Python, hai từ khóa này bắt buộc phải viết hoa chữ cái đầu (True, False), viết thường (true, false) sẽ bị báo lỗi cú pháp.")
print("+ Chúng thường là kết quả trả về của các phép toán so sánh hoặc các biểu thức logic và đóng vai trò làm điều kiện quyết định cho mệnh đề điều kiện (if...else) hoặc vòng lặp (while). viết code python để khi chạy được như này")